model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val_loss # quantity to monitor
  dirpath: ${paths.ckpt_dir} # directory to save checkpoints
  filename: "{epoch}-{step}" # checkpoint filename
  every_n_epochs: 1 # number of epochs between checkpoints