_target_: scgenescope.models.nn.sets.DeepSet.with_fixed_hidden_dim
input_dim: ???
hidden_dim: ???
output_dim: ???
elementwise_depth: ???
num_layers: ???
aggregation: ???
conditioning: ???
readout: ???
residual: ???
